apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-nginx
  name: ingress-monitor
  namespace: ingress
spec:
  ports:
  - name: ingress-nginx
    port: 10254
    protocol: TCP
    targetPort: 10254
  selector:
    app: ingress-nginx
  type: ClusterIP
