apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager
  labels:
    k8s-app: kube-controller-manager
spec:
  selector:
    component: kube-controller-manager
  ports:
  - name: http-metrics
    port: 10252
    targetPort: 10252


#修改 kube-controller-manager 配置，/etc/kubernetes/manifests/kube-controller-manager.yaml，
#--bind-address=0.0.0.0  #改为0.0.0.0