apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter
        args:
        - -include-system-metrics=true
        ports:
        - containerPort: 9121
          protocol: TCP
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: REDIS_ADDR
          value: redis://REDIS_HOST:6379
        - name: REDIS_PASSWORD
          value: ""
