apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jvm-monitor
  namespace: monitoring
  labels:
    app: pod-jvm
spec:
  #jobLabel: app
  endpoints:
  - port: jvm-monitor
    interval: 15s
    scheme: http
    path: '/metrics'
  selector:
    matchLabels:
      app: pod-jvm
  namespaceSelector:
    any: true
